apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "kafka-mirror-maker"
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: internal-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{name}}-kafka-mirror-maker"
    spec:
      destination:
        server: "{{server}}"
      project: core-sre
      source:
        path: sre/mirror-maker/{{name}}
        repoURL: https://github.com/Raj-prateek/strimzi-kafka-argocd.git
        targetRevision: main
