apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "strimzi-kafka-operator"
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: internal-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{cluster}}-strimzi-kafka-operator"
    spec:
      destination:
        server: "{{url}}"
        namespace: strimzi
      project: core-sre
      source:
        chart: "strimzi/strimzi-kafka-operator"
        repoURL: "https://strimzi.io/charts"
        targetRevision: 0.36.0
        helm:
          releaseName: strimzi
          parameters:
            - name: "watchAnyNamespace"
              value: "true"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
