apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "strimzi-kafka-operator"
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            brevo.com/cluster.with.strimzi.kafka: "true"
  template:
    metadata:
      name: "{{name}}-strimzi-kafka-operator"
    spec:
      destination:
        server: "{{server}}"
        namespace: strimzi
      project: core-sre
      source:
        chart: strimzi/strimzi-kafka-operator
        repoURL: https://strimzi.io/charts/
        targetRevision: 0.36.0
        helm:
          releaseName: strimzi
          parameters:
            - name: "watchAnyNamespace"
              value: "true"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
