apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-sre
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: This project host all the apps handled by the Core SRE team. Reach us on slack @core-sre.
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}
